#!/usr/bin/env python3.7
# BMI = (weight in kg / height in m ^2)

def gather_info():
  height = float(input("what is your height? (inches or metres) "))
  weight = float(input("what is your weight? (lbs or kgs) "))
  system = input("Are your measurements in metric or imperial units?".lower().strip())
  return (height,weight,system)

def calculate_bmi(weight, height, system='metric'):
  """
  Return the Body mass index for the given weight and height and system
  """
  if system=='metric':
    bmi = (weight/(height**2))
  else:
    bmi = 703 * (weight / (height**2))
  return bmi

while True:
  height, weight, system = gather_info()
  if system.startswith('i'):
    bmi = calculate_bmi(weight,system=system, height=height)
    print(f"Your bmi is {bmi}")
    break
  elif system.startswith('m'):
    bmi = calculate_bmi(weight,height)
    print(f"Your bmi is {bmi} ")
    break
  else:
    print("Error: unknown system, please try again")
