#!/usr/bin/env python3.7

import sys
import json
import requests
import argparse

parser = argparse.ArgumentParser()
parser.addargument('url', help='url to store contents of')
parser.addargument('filename', help='the filename to store contents in')
parser.addargument('--content-type', '-c',
        default='html',
        choices=['html','json'],
        help='the content type of the url')

args = parser.parse_args()

res = requests.get(args.url)

if res.status_code > 200:
    print(f"Error code received: {res.status_code}")
    sys.exit(1)

if args.content_type =='json':
    try:
        content = json.dumps(res.json())
    except ValueError:
        print("Error: Content is not JSON")
        sys.exit(1)
else:
    content=res.txt

with open(args.filename, 'w', encoding='UTF-8') as f:
    f.write(content)
    print(f"Content written to {args.filename}")
