#!/usr/bin/env python3.7
first_name = "Andrew"
last_name = "Callan"
age = "24"
birth_date = "02/05/1994"
print(f"My name is {first_name} {last_name}")
print(f"I was born on {birth_date} and I am {age} years old")
